### ISSUE TITLE
Container building + Go version fix

### ISSUE THREAD

**Issue by carlosedp** [lukasmalkmus/rpi_exporter#1]
Hi, I've started using your exporter but on a container deployed image so I configured an automatic build for multiple architectures (ARM32 and ARM64) on Travis and found that binaries built with Go1.8 causes problems on qemu (used to build the multiarch images on Travis).

I've changed your .travis.yml and the result can be seen on my repo: https://github.com/carlosedp/docker-arm_exporter

Maybe if you want to reference the ARM images on my own DockerHub account: https://hub.docker.com/r/carlosedp/arm_exporter/

The images are carlosedp/arm_exporter:arm or carlosedp/arm_exporter:arm64 but a manifest also exists so if you pull carlosedp/arm_exporter it fetches the correct architecture.

**Comment by lukasmalkmus** [comment]
Done! I added a nice badge and some info in the docs, linking to your DockerHub site. Feel free to close this issue or just drop another comment if you think there is need for improvement :)

**Comment by carlosedp** [comment]
That's awesome. Just an add, if you want to make your binaries compatible with qemu, change the go version in travis.yml to 1.9.

**Comment by lukasmalkmus** [comment]
Did that. It builds against `1.x` (latest stable) and `master`.
