### ISSUE TITLE
vcgencmd not included in docker image

### ISSUE THREAD

**Issue by gclawes** [lukasmalkmus/rpi_exporter#11]
The docker image provided cannont get GPU temperature, as the `vcgencmd` utility is not installed:
```
ubuntu@pi01:~$ docker run -p 9243:9243 carlosedp/arm_exporter
No /etc/nodename has been set, running with no nodename identifier.
time="2020-04-14T12:39:07Z" level=info msg="Starting rpi_exporter(version=, branch=, revision=)" source="rpi_exporter.go:82"
time="2020-04-14T12:39:07Z" level=info msg="Build context(go=go1.12.7, user=, date=)" source="rpi_exporter.go:83"
time="2020-04-14T12:39:07Z" level=info msg="Listening on:9243" source="rpi_exporter.go:115"
time="2020-04-14T12:39:15Z" level=error msg="gpu collector failed after 0.002923s: fork/exec /opt/vc/bin/vcgencmd: no such file or directory" source="collector.go:142"
```

**Comment by lukasmalkmus** [comment]
https://github.com/carlosedp/docker-arm_exporter/issues/4

Tbh, I never thought about that. Maybe try mounting the binary from the host?

**Comment by gclawes** [comment]
Unfortunately the host isn't guaranteed to have it, Ubuntu 19.10 64-bit doesn't yet have a PPA for the Raspberry Pi userland.  Mounting the binary in would only work if it's statically compiled, which I'm not sure it is.

**Comment by huntipl** [comment]
Adding `RUN apk add raspberrypi` to dockerfile for Alpine seems to install all required libraries for it to work, you also have to mount `/dev/vchiq` as @gclawes mentioned in the linked issue

**Comment by lukasmalkmus** [comment]
Closing since this is docker related and discussed and resolved in https://github.com/carlosedp/docker-arm_exporter/issues/4.
