### ISSUE TITLE
New registry is created for every request

### ISSUE THREAD

**Issue by ToMe25** [lukasmalkmus/rpi_exporter#22]
Currently this exporter creates a new collector registry for every request.
I believe it would be better to create the unfiltered handler once, and store it, like node_exporter does.

I will make a PR for that later(probably tomorrow), I just wanted to let you know in case you wanted to wait for this before releasing the next version :)

**Comment by lukasmalkmus** [comment]
Feel free to do a PR. I'll haven't managed to test the latest changes on my local device, unfortunately. So let's for your next PR to land :)
