### ISSUE TITLE
Grafana

### ISSUE THREAD

**Issue by crsCR** [lukasmalkmus/rpi_exporter#6]
Hi - thanks for this exporter. Would be great if you could give instructions in the readme for those new to Prometheus that want to see the temp metric displayed in Grafana somehow...

**Comment by lukasmalkmus** [comment]
I don't think my README is the right place for giving a detailed instruction on how to get the metrics into Grafana. There are plenty of resources available.

The exporter listens for requests on port `9243`. So point your Prometheus server there to collect metrics from the exporter: https://prometheus.io/docs/prometheus/latest/configuration/configuration/

Then how up Prometheus with Grafana: https://www.prometheus.io/docs/visualization/grafana/
