### ISSUE TITLE
Exporter doesn't show version in build_info metric

### ISSUE THREAD

**Issue by paulfantom** [lukasmalkmus/rpi_exporter#8]
Currently (tarball from release 0.6.0) exporter shows metric:
```
rpi_exporter_build_info{branch="",goversion="go1.12.7",revision="",version=""} 1
```
which doesn't populate either `branch` nor `version` labels. It would be nice if at least `version` was exposed.

**Comment by paulfantom** [comment]
This can be done by properly implementing https://godoc.org/github.com/prometheus/client_golang/prometheus#NewBuildInfoCollector with conjunction of `-X` build variables (those are usually set by promu).

**Comment by lukasmalkmus** [comment]
When transitioning to go modules I forgot to correctly address the `version` package. This has been fixed with a recent commit and will be included in a release I cut very soon.
